// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOGcFBQLvXqPDSZYMFf86X8Hy6g7ywfo4',
    appId: '1:435717014101:web:0bd68abc8a00cd5aab0adc',
    messagingSenderId: '435717014101',
    projectId: 'back-end-work',
    authDomain: 'back-end-work.firebaseapp.com',
    databaseURL: 'https://back-end-work-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'back-end-work.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrMeagyjgN18ZoKLa9fUVTMzhlam8Hntg',
    appId: '1:435717014101:android:9069a82f416f17d1ab0adc',
    messagingSenderId: '435717014101',
    projectId: 'back-end-work',
    databaseURL: 'https://back-end-work-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'back-end-work.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWzC7lju8yMVtU9cnq6fJezxgJN0FXYls',
    appId: '1:435717014101:ios:a1461423825bf111ab0adc',
    messagingSenderId: '435717014101',
    projectId: 'back-end-work',
    databaseURL: 'https://back-end-work-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'back-end-work.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWzC7lju8yMVtU9cnq6fJezxgJN0FXYls',
    appId: '1:435717014101:ios:a1461423825bf111ab0adc',
    messagingSenderId: '435717014101',
    projectId: 'back-end-work',
    databaseURL: 'https://back-end-work-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'back-end-work.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOGcFBQLvXqPDSZYMFf86X8Hy6g7ywfo4',
    appId: '1:435717014101:web:6d8507afedd9c540ab0adc',
    messagingSenderId: '435717014101',
    projectId: 'back-end-work',
    authDomain: 'back-end-work.firebaseapp.com',
    databaseURL: 'https://back-end-work-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'back-end-work.appspot.com',
  );
}
